apiVersion: v1
kind: Pod
metadata: 
  name: multi-container
  namespace: roboshop
spec:
  containers:
    - name:  nginx
      image: nginx
    - name: almalinux
      image: alamlinux:9
      command: ["sleep", "1000"] # comment this run and uncomment this and run again