apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    project: roboshop
    component:  frontend
  annotations:
    imageregistry: "http://"
    jenkinsURL: "http://"
spec:
  containers:
    - name: nginx
      image: nginx      