apiVersion: v1
kind: Pod
metadata:
  name: env-demo
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef: 
        name: nginx-config
    


# Structure your repo like:

# k8s/
#   config/
#     configmap.yaml   👈 central config
#   deployments/
#     app1.yaml
#     app2.yaml

#     kubectl apply -f k8s/config/
# kubectl apply -f k8s/deployments/
# 👉 Config gets created once → reused everywhere
# ✔️ Use Kustomize

# You can define shared config in one place:

# configMapGenerator:
#   - name: app-config
#     literals:
#       - DB_HOST=mysql
#       - LOG_LEVEL=debug

# Then reuse across multiple manifests.