apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
data:
  username: "EJDNM3K" #SAMPLE ENCODED VALUE OD A WORD
  password: "DSHFSHDFH"


  # in shell echo "hello" | base64
    ----gives encoded value, give it above